### PR TITLE
Ay - updated SQL file

### PR DESCRIPTION
**Pull request by AdelaideYoder**
Please structure your pull requests this way:

- **Purpose of PR**
Columns needed to be added to tables in the SQL file

- **Issue number this request impacts** ------
#22, #6, #15

- **Description of what was changed:**
Added in Description for Training Program Table
Added in Manufacturer and Model for Computer Table and changed column Condition to allow null values
Added in StartDate, EndDate for Employee Table

Added updated ERD, to match changes

Deleted parts of the employee controller to be a blank model so that we don't get conflicts when running program

Changed Employee to Employees in the Department model

Changed the FK names on the EmployeeComputer table to:
FK_EmployeeComputer_Employee
FK_EmployeeComputer_Computer

- **Thorough list of steps to test**

1. Checkout to master
2. Fetch All
3. Checkout into ay-updated-SQL
4. LS to find SQL file
5. Start SQL file
6. Run/Execute file with no errors

if you don't do this you will be
**FIRED**

### CODE REVIEW

**Comment by AdelaideYoder** [comment]
Here is our updated ERD
erd-sprint2

**Comment by jisie** [comment]
Changed what condition to null???

**Comment by jisie** [comment]
Also, there are changes other than the modifications to the sql file in this pull request. Either add that to the pull request description or create a new pull request for them.

**Comment by AdelaideYoder** [comment]
ERD has been updated to match changes
erd-sprint2

**Pull request merged**
